import { ValueType } from '@prisma/client';

export const OBD_PID_CATALOG_SEED: Array<{
  mode: string;
  pidCode: string;
  fullCode: string;
  key: string;
  label: string;
  unit: string | null;
  valueType: ValueType;
  description: string;
  formula: string | null;
  isMandatory: boolean;
}> = [
  {
    mode: '01',
    pidCode: '0C',
    fullCode: '010C',
    key: 'engine_rpm',
    label: 'Engine RPM',
    unit: 'rpm',
    valueType: ValueType.NUMBER,
    description: 'Engine speed in revolutions per minute.',
    formula: '(256A + B) / 4',
    isMandatory: true,
  },
  {
    mode: '01',
    pidCode: '0D',
    fullCode: '010D',
    key: 'vehicle_speed',
    label: 'Vehicle Speed',
    unit: 'km/h',
    valueType: ValueType.NUMBER,
    description: 'Vehicle speed reported by the ECU.',
    formula: 'A',
    isMandatory: true,
  },
  {
    mode: '01',
    pidCode: '04',
    fullCode: '0104',
    key: 'engine_load',
    label: 'Calculated Engine Load',
    unit: '%',
    valueType: ValueType.NUMBER,
    description: 'Calculated engine load percentage.',
    formula: '(A * 100) / 255',
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '05',
    fullCode: '0105',
    key: 'coolant_temp_c',
    label: 'Engine Coolant Temperature',
    unit: 'C',
    valueType: ValueType.NUMBER,
    description: 'Coolant temperature in Celsius.',
    formula: 'A - 40',
    isMandatory: true,
  },
  {
    mode: '01',
    pidCode: '06',
    fullCode: '0106',
    key: 'short_term_fuel_trim_bank1',
    label: 'Short Term Fuel Trim Bank 1',
    unit: '%',
    valueType: ValueType.NUMBER,
    description: 'Short-term fuel trim for bank 1.',
    formula: '((A - 128) * 100) / 128',
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '07',
    fullCode: '0107',
    key: 'long_term_fuel_trim_bank1',
    label: 'Long Term Fuel Trim Bank 1',
    unit: '%',
    valueType: ValueType.NUMBER,
    description: 'Long-term fuel trim for bank 1.',
    formula: '((A - 128) * 100) / 128',
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '0F',
    fullCode: '010F',
    key: 'intake_air_temp_c',
    label: 'Intake Air Temperature',
    unit: 'C',
    valueType: ValueType.NUMBER,
    description: 'Intake air temperature.',
    formula: 'A - 40',
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '10',
    fullCode: '0110',
    key: 'maf_g_s',
    label: 'Mass Air Flow',
    unit: 'g/s',
    valueType: ValueType.NUMBER,
    description: 'Mass air flow rate.',
    formula: '(256A + B) / 100',
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '0B',
    fullCode: '010B',
    key: 'intake_manifold_pressure_kpa',
    label: 'Intake Manifold Pressure',
    unit: 'kPa',
    valueType: ValueType.NUMBER,
    description: 'Absolute intake manifold pressure.',
    formula: 'A',
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '11',
    fullCode: '0111',
    key: 'throttle_position_pct',
    label: 'Throttle Position',
    unit: '%',
    valueType: ValueType.NUMBER,
    description: 'Absolute throttle position.',
    formula: '(A * 100) / 255',
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '42',
    fullCode: '0142',
    key: 'control_module_voltage_v',
    label: 'Control Module Voltage',
    unit: 'V',
    valueType: ValueType.NUMBER,
    description: 'Vehicle control module voltage.',
    formula: '(256A + B) / 1000',
    isMandatory: false,
  },
  {
    mode: '03',
    pidCode: '00',
    fullCode: '0300',
    key: 'stored_dtcs',
    label: 'Stored Diagnostic Trouble Codes',
    unit: null,
    valueType: ValueType.JSON,
    description: 'Stored diagnostic trouble codes.',
    formula: null,
    isMandatory: false,
  },
  {
    mode: '07',
    pidCode: '00',
    fullCode: '0700',
    key: 'pending_dtcs',
    label: 'Pending Diagnostic Trouble Codes',
    unit: null,
    valueType: ValueType.JSON,
    description: 'Pending diagnostic trouble codes.',
    formula: null,
    isMandatory: false,
  },
  {
    mode: '0A',
    pidCode: '00',
    fullCode: '0A00',
    key: 'permanent_dtcs',
    label: 'Permanent Diagnostic Trouble Codes',
    unit: null,
    valueType: ValueType.JSON,
    description: 'Permanent diagnostic trouble codes.',
    formula: null,
    isMandatory: false,
  },
];
