import { ValueType } from '@prisma/client';

export const OBD_PID_CATALOG_SEED: Array<{
  mode: string;
  pidCode: string;
  fullCode: string;
  key: string;
  label: string;
  unit: string | null;
  valueType: ValueType;
  description: string;
  formula: string | null;
  isMandatory: boolean;
}> = [
  {
    mode: '01',
    pidCode: '00',
    fullCode: '0100',
    key: 'supported_pids_01_20',
    label: "Supported PIDs 01–20",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Bitmask of which PIDs 01–20 this ECU supports. Always query this first before polling.",
    formula: "32-bit bitmask",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '01',
    fullCode: '0101',
    key: 'monitor_status_mil',
    label: "Monitor status (MIL)",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Check Engine Light status, number of DTCs stored, and readiness monitor states for each emission system.",
    formula: "See SAE J1979",
    isMandatory: true,
  },
  {
    mode: '01',
    pidCode: '02',
    fullCode: '0102',
    key: 'freeze_frame_dtc',
    label: "Freeze frame DTC",
    unit: "—",
    valueType: ValueType.STRING,
    description: "The DTC that triggered the current freeze frame snapshot.",
    formula: "—",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '03',
    fullCode: '0103',
    key: 'fuel_system_status',
    label: "Fuel system status",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Open or closed loop status for fuel system on each bank. Closed = ECU using O2 sensor feedback.",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '04',
    fullCode: '0104',
    key: 'engine_load',
    label: "Engine load",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Calculated engine load as % of peak available torque. High values under light throttle suggest a problem.",
    formula: "A / 2.55",
    isMandatory: true,
  },
  {
    mode: '01',
    pidCode: '05',
    fullCode: '0105',
    key: 'coolant_temp_c',
    label: "Coolant temperature",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Engine coolant temperature. Essential for warm-up diagnostics and fan control monitoring.",
    formula: "A − 40",
    isMandatory: true,
  },
  {
    mode: '01',
    pidCode: '06',
    fullCode: '0106',
    key: 'short_term_fuel_trim_bank1',
    label: "Short-term fuel trim B1",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Short-term fuel correction for bank 1. +10% = adding fuel (lean). −10% = reducing fuel (rich).",
    formula: "A/1.28 − 100",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '07',
    fullCode: '0107',
    key: 'long_term_fuel_trim_bank1',
    label: "Long-term fuel trim B1",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Learned long-term correction for bank 1. Large values indicate a persistent fuel delivery issue.",
    formula: "A/1.28 − 100",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '08',
    fullCode: '0108',
    key: 'short_term_fuel_trim_bank2',
    label: "Short-term fuel trim B2",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Short-term fuel correction for bank 2 (V-engines only).",
    formula: "A/1.28 − 100",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '09',
    fullCode: '0109',
    key: 'long_term_fuel_trim_bank2',
    label: "Long-term fuel trim B2",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Learned correction for bank 2.",
    formula: "A/1.28 − 100",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '0A',
    fullCode: '010A',
    key: 'fuel_pressure_kpa',
    label: "Fuel pressure",
    unit: "kPa",
    valueType: ValueType.NUMBER,
    description: "Fuel rail or fuel line pressure at the injectors.",
    formula: "A × 3",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '0B',
    fullCode: '010B',
    key: 'intake_manifold_pressure_kpa',
    label: "Intake manifold pressure",
    unit: "kPa",
    valueType: ValueType.NUMBER,
    description: "Absolute pressure in intake manifold (MAP sensor). Used with MAF for load calculation.",
    formula: "A",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '0C',
    fullCode: '010C',
    key: 'engine_rpm',
    label: "Engine RPM",
    unit: "RPM",
    valueType: ValueType.NUMBER,
    description: "Engine rotational speed. Fundamental for tachometer and rev-matching logic.",
    formula: "(256A + B) / 4",
    isMandatory: true,
  },
  {
    mode: '01',
    pidCode: '0D',
    fullCode: '010D',
    key: 'vehicle_speed',
    label: "Vehicle speed",
    unit: "km/h",
    valueType: ValueType.NUMBER,
    description: "Vehicle speed reported by the ECU from transmission or wheel speed sensors.",
    formula: "A",
    isMandatory: true,
  },
  {
    mode: '01',
    pidCode: '0E',
    fullCode: '010E',
    key: 'timing_advance_deg',
    label: "Timing advance",
    unit: "°",
    valueType: ValueType.NUMBER,
    description: "Spark ignition timing advance relative to TDC (top dead center) on cylinder 1.",
    formula: "A/2 − 64",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '0F',
    fullCode: '010F',
    key: 'intake_air_temp_c',
    label: "Intake air temperature",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Air temperature at the intake manifold. Affects fuel injection calculation.",
    formula: "A − 40",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '10',
    fullCode: '0110',
    key: 'maf_g_s',
    label: "MAF air flow rate",
    unit: "g/s",
    valueType: ValueType.NUMBER,
    description: "Mass air flow sensor — grams of air entering engine per second. Key for fuel calculation.",
    formula: "(256A + B) / 100",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '11',
    fullCode: '0111',
    key: 'throttle_position_pct',
    label: "Throttle position",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Absolute throttle plate position as reported by the TPS sensor.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '12',
    fullCode: '0112',
    key: 'secondary_air_status',
    label: "Secondary air status",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Status of secondary air injection system (emissions control).",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '13',
    fullCode: '0113',
    key: 'oxygen_sensors_present',
    label: "O2 sensors present",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Bitmask indicating which O2 sensor positions exist on this vehicle.",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '14',
    fullCode: '0114',
    key: 'o2_sensor_b1s1',
    label: "O2 sensor B1S1",
    unit: "V, %",
    valueType: ValueType.JSON,
    description: "Pre-catalytic oxygen sensor bank 1. Voltage and short-term trim.",
    formula: "A/200, (B/1.28−100)",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '15',
    fullCode: '0115',
    key: 'o2_sensor_b1s2',
    label: "O2 sensor B1S2",
    unit: "V, %",
    valueType: ValueType.JSON,
    description: "Post-catalytic O2 sensor bank 1. Used to check catalyst efficiency.",
    formula: "A/200, (B/1.28−100)",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '16',
    fullCode: '0116',
    key: 'o2_sensor_b1s3',
    label: "O2 sensor B1S3",
    unit: "V, %",
    valueType: ValueType.JSON,
    description: "Bank 1 sensor 3.",
    formula: "A/200, (B/1.28−100)",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '17',
    fullCode: '0117',
    key: 'o2_sensor_b1s4',
    label: "O2 sensor B1S4",
    unit: "V, %",
    valueType: ValueType.JSON,
    description: "Bank 1 sensor 4.",
    formula: "A/200, (B/1.28−100)",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '18',
    fullCode: '0118',
    key: 'o2_sensor_b2s1',
    label: "O2 sensor B2S1",
    unit: "V, %",
    valueType: ValueType.JSON,
    description: "Pre-cat O2 bank 2 (V-engines, passenger side).",
    formula: "A/200, (B/1.28−100)",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '19',
    fullCode: '0119',
    key: 'o2_sensor_b2s2',
    label: "O2 sensor B2S2",
    unit: "V, %",
    valueType: ValueType.JSON,
    description: "Post-cat O2 sensor bank 2.",
    formula: "A/200, (B/1.28−100)",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '1C',
    fullCode: '011C',
    key: 'obd_standard',
    label: "OBD standard",
    unit: "—",
    valueType: ValueType.STRING,
    description: "Which OBD standard this vehicle was designed to comply with (OBD-II, EOBD, OBD-I, etc.).",
    formula: "Enum",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '1F',
    fullCode: '011F',
    key: 'runtime_since_engine_start_s',
    label: "Run time since engine start",
    unit: "s",
    valueType: ValueType.NUMBER,
    description: "How long the engine has been running since last cold start.",
    formula: "256A + B",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '20',
    fullCode: '0120',
    key: 'supported_pids_21_40',
    label: "Supported PIDs 21–40",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Bitmask of supported PIDs in the 21–40 range.",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '21',
    fullCode: '0121',
    key: 'distance_with_mil_on_km',
    label: "Distance with MIL on",
    unit: "km",
    valueType: ValueType.NUMBER,
    description: "Cumulative distance driven with Check Engine Light illuminated.",
    formula: "256A + B",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '22',
    fullCode: '0122',
    key: 'fuel_rail_pressure_relative_kpa',
    label: "Fuel rail pressure (relative)",
    unit: "kPa",
    valueType: ValueType.NUMBER,
    description: "Fuel rail pressure relative to intake manifold vacuum.",
    formula: "(256A+B) × 0.079",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '23',
    fullCode: '0123',
    key: 'fuel_rail_pressure_direct_kpa',
    label: "Fuel rail pressure (direct)",
    unit: "kPa",
    valueType: ValueType.NUMBER,
    description: "Absolute fuel rail pressure (diesel and GDI gasoline engines).",
    formula: "(256A+B) × 10",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '2C',
    fullCode: '012C',
    key: 'egr_commanded_pct',
    label: "EGR commanded",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Commanded position of Exhaust Gas Recirculation valve.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '2D',
    fullCode: '012D',
    key: 'egr_error_pct',
    label: "EGR error",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Difference between commanded and actual EGR valve position.",
    formula: "A/1.28 − 100",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '2E',
    fullCode: '012E',
    key: 'evap_purge_commanded_pct',
    label: "Evap purge commanded",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Duty cycle of evaporative emission purge valve.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '2F',
    fullCode: '012F',
    key: 'fuel_tank_level_pct',
    label: "Fuel tank level",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Remaining fuel in tank as a percentage of full capacity.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '30',
    fullCode: '0130',
    key: 'warmups_since_codes_cleared',
    label: "Warm-ups since codes cleared",
    unit: "count",
    valueType: ValueType.NUMBER,
    description: "Number of complete warm-up cycles since DTCs were last cleared.",
    formula: "A",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '31',
    fullCode: '0131',
    key: 'distance_since_codes_cleared_km',
    label: "Distance since codes cleared",
    unit: "km",
    valueType: ValueType.NUMBER,
    description: "Total distance driven since DTCs were last cleared.",
    formula: "256A + B",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '33',
    fullCode: '0133',
    key: 'barometric_pressure_kpa',
    label: "Barometric pressure",
    unit: "kPa",
    valueType: ValueType.NUMBER,
    description: "Absolute atmospheric pressure from baro sensor or ECU model.",
    formula: "A",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '3C',
    fullCode: '013C',
    key: 'catalyst_temp_b1s1_c',
    label: "Catalyst temp B1S1",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Temperature of catalytic converter bank 1 inlet sensor.",
    formula: "(256A+B)/10 − 40",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '3D',
    fullCode: '013D',
    key: 'catalyst_temp_b2s1_c',
    label: "Catalyst temp B2S1",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Catalyst temperature bank 2 inlet.",
    formula: "(256A+B)/10 − 40",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '3E',
    fullCode: '013E',
    key: 'catalyst_temp_b1s2_c',
    label: "Catalyst temp B1S2",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Catalyst temperature bank 1 outlet sensor.",
    formula: "(256A+B)/10 − 40",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '3F',
    fullCode: '013F',
    key: 'catalyst_temp_b2s2_c',
    label: "Catalyst temp B2S2",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Catalyst temperature bank 2 outlet.",
    formula: "(256A+B)/10 − 40",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '40',
    fullCode: '0140',
    key: 'supported_pids_41_60',
    label: "Supported PIDs 41–60",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Bitmask of supported PIDs in the 41–60 range.",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '42',
    fullCode: '0142',
    key: 'control_module_voltage_v',
    label: "Control module voltage",
    unit: "V",
    valueType: ValueType.NUMBER,
    description: "Battery/supply voltage as measured by the ECU control module.",
    formula: "(256A+B) / 1000",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '43',
    fullCode: '0143',
    key: 'absolute_engine_load_pct',
    label: "Absolute engine load",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Normalized air mass per intake stroke as a percentage of peak.",
    formula: "(256A+B) / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '44',
    fullCode: '0144',
    key: 'commanded_air_fuel_ratio_lambda',
    label: "Commanded air-fuel ratio",
    unit: "λ",
    valueType: ValueType.NUMBER,
    description: "Target lambda (air-fuel ratio) commanded by the ECU.",
    formula: "(256A+B) / 32768",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '45',
    fullCode: '0145',
    key: 'relative_throttle_position_pct',
    label: "Relative throttle position",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Throttle position relative to the learned closed position.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '46',
    fullCode: '0146',
    key: 'ambient_air_temp_c',
    label: "Ambient air temperature",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Outside air temperature from external ambient sensor.",
    formula: "A − 40",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '47',
    fullCode: '0147',
    key: 'absolute_throttle_position_b_pct',
    label: "Absolute throttle position B",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Second throttle sensor for drive-by-wire dual-sensor systems.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '4C',
    fullCode: '014C',
    key: 'commanded_throttle_actuator_pct',
    label: "Commanded throttle actuator",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Duty cycle commanded to the electronic throttle actuator motor.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '4D',
    fullCode: '014D',
    key: 'time_with_mil_on_min',
    label: "Time with MIL on",
    unit: "min",
    valueType: ValueType.NUMBER,
    description: "Cumulative time the Check Engine Light has been illuminated.",
    formula: "256A + B",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '4E',
    fullCode: '014E',
    key: 'time_since_codes_cleared_min',
    label: "Time since codes cleared",
    unit: "min",
    valueType: ValueType.NUMBER,
    description: "Total time elapsed since trouble codes were last cleared.",
    formula: "256A + B",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '51',
    fullCode: '0151',
    key: 'fuel_type',
    label: "Fuel type",
    unit: "—",
    valueType: ValueType.STRING,
    description: "Type of fuel in use: gasoline, diesel, ethanol, LPG, CNG, hybrid, etc.",
    formula: "Enum",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '52',
    fullCode: '0152',
    key: 'ethanol_fuel_pct',
    label: "Ethanol fuel %",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Percentage of ethanol in the fuel blend (flex-fuel vehicles).",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '5A',
    fullCode: '015A',
    key: 'relative_accelerator_pedal_pct',
    label: "Relative accelerator pedal",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Relative position of the accelerator pedal sensor.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '5B',
    fullCode: '015B',
    key: 'hybrid_battery_pack_life_pct',
    label: "Hybrid battery pack life",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "State of health of the hybrid or EV traction battery pack.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '5C',
    fullCode: '015C',
    key: 'engine_oil_temp_c',
    label: "Engine oil temperature",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Oil sump temperature. Critical for oil viscosity and engine wear analysis.",
    formula: "A − 40",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '5D',
    fullCode: '015D',
    key: 'fuel_injection_timing_deg',
    label: "Fuel injection timing",
    unit: "°",
    valueType: ValueType.NUMBER,
    description: "Fuel injection timing angle relative to TDC.",
    formula: "(256A+B)/128 − 210",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '5E',
    fullCode: '015E',
    key: 'engine_fuel_rate_lph',
    label: "Engine fuel rate",
    unit: "L/h",
    valueType: ValueType.NUMBER,
    description: "Volume of fuel consumed per hour at current operating point.",
    formula: "(256A+B) / 20",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '60',
    fullCode: '0160',
    key: 'supported_pids_61_80',
    label: "Supported PIDs 61–80",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Bitmask of supported PIDs in the 61–80 range.",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '67',
    fullCode: '0167',
    key: 'coolant_temp_sensor_2_c',
    label: "Engine coolant temp (sensor 2)",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Coolant temperature from a secondary sensor.",
    formula: "(256A+B)/128 − 40",
    isMandatory: false,
  },
  {
    mode: '01',
    pidCode: '68',
    fullCode: '0168',
    key: 'fuel_rail_absolute_pressure_kpa',
    label: "Fuel rail absolute pressure",
    unit: "kPa",
    valueType: ValueType.NUMBER,
    description: "Absolute fuel rail pressure (3-byte high-res version).",
    formula: "(A×65536+B×256+C)×0.079",
    isMandatory: false,
  },
  {
    mode: '02',
    pidCode: '00',
    fullCode: '0200',
    key: 'freeze_frame_supported_pids',
    label: "Freeze frame supported PIDs",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Bitmask of freeze frame PIDs available for the stored DTC.",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '02',
    pidCode: '01',
    fullCode: '0201',
    key: 'freeze_frame_dtc_at_fault',
    label: "Freeze frame DTC",
    unit: "—",
    valueType: ValueType.STRING,
    description: "The diagnostic trouble code that triggered this freeze frame record.",
    formula: "—",
    isMandatory: false,
  },
  {
    mode: '02',
    pidCode: '04',
    fullCode: '0204',
    key: 'freeze_engine_load_pct',
    label: "Freeze: Engine load",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Engine load percentage at time of fault.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '02',
    pidCode: '05',
    fullCode: '0205',
    key: 'freeze_coolant_temp_c',
    label: "Freeze: Coolant temperature",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Coolant temp at time of fault.",
    formula: "A − 40",
    isMandatory: false,
  },
  {
    mode: '02',
    pidCode: '0C',
    fullCode: '020C',
    key: 'freeze_engine_rpm',
    label: "Freeze: Engine RPM",
    unit: "RPM",
    valueType: ValueType.NUMBER,
    description: "RPM at time of fault.",
    formula: "(256A+B)/4",
    isMandatory: false,
  },
  {
    mode: '02',
    pidCode: '0D',
    fullCode: '020D',
    key: 'freeze_vehicle_speed',
    label: "Freeze: Vehicle speed",
    unit: "km/h",
    valueType: ValueType.NUMBER,
    description: "Speed at time of fault.",
    formula: "A",
    isMandatory: false,
  },
  {
    mode: '02',
    pidCode: '0F',
    fullCode: '020F',
    key: 'freeze_intake_air_temp_c',
    label: "Freeze: Intake air temp",
    unit: "°C",
    valueType: ValueType.NUMBER,
    description: "Intake air temperature at fault moment.",
    formula: "A − 40",
    isMandatory: false,
  },
  {
    mode: '02',
    pidCode: '10',
    fullCode: '0210',
    key: 'freeze_maf_g_s',
    label: "Freeze: MAF air flow",
    unit: "g/s",
    valueType: ValueType.NUMBER,
    description: "Mass air flow at fault moment.",
    formula: "(256A+B)/100",
    isMandatory: false,
  },
  {
    mode: '02',
    pidCode: '11',
    fullCode: '0211',
    key: 'freeze_throttle_position_pct',
    label: "Freeze: Throttle position",
    unit: "%",
    valueType: ValueType.NUMBER,
    description: "Throttle position at fault moment.",
    formula: "A / 2.55",
    isMandatory: false,
  },
  {
    mode: '03',
    pidCode: '00',
    fullCode: '0300',
    key: 'stored_dtcs',
    label: "Request stored DTCs",
    unit: null,
    valueType: ValueType.JSON,
    description: "Returns all confirmed DTCs. Each code is 2 bytes. Format: Pxxxx=Powertrain, Bxxxx=Body, Cxxxx=Chassis, Uxxxx=Network. P0xxx = SAE standard codes. P1xxx = OEM proprietary.",
    formula: "—",
    isMandatory: true,
  },
  {
    mode: '04',
    pidCode: '00',
    fullCode: '0400',
    key: 'clear_dtcs_reset_monitors',
    label: "Clear DTCs & reset monitors",
    unit: "—",
    valueType: ValueType.NUMBER,
    description: "⚠️ Permanently clears all stored and pending DTCs, resets all readiness monitors to \"not ready\", and erases freeze frame data. After this, the engine must complete a full drive cycle for monitors to re-run. Do not use right before an emissions inspection.",
    formula: "—",
    isMandatory: true,
  },
  {
    mode: '05',
    pidCode: '00',
    fullCode: '0500',
    key: 'o2_test_supported',
    label: "O2 test supported",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Bitmask of which O2 sensor tests are available on this vehicle.",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '05',
    pidCode: '01',
    fullCode: '0501',
    key: 'o2_rich_to_lean_threshold_v',
    label: "Rich-to-lean threshold voltage",
    unit: "V",
    valueType: ValueType.NUMBER,
    description: "O2 sensor voltage threshold for rich-to-lean transition test.",
    formula: "A / 200",
    isMandatory: false,
  },
  {
    mode: '05',
    pidCode: '02',
    fullCode: '0502',
    key: 'o2_lean_to_rich_threshold_v',
    label: "Lean-to-rich threshold voltage",
    unit: "V",
    valueType: ValueType.NUMBER,
    description: "O2 sensor threshold for lean-to-rich transition.",
    formula: "A / 200",
    isMandatory: false,
  },
  {
    mode: '05',
    pidCode: '03',
    fullCode: '0503',
    key: 'o2_test_low_sensor_voltage_v',
    label: "Low sensor voltage for test",
    unit: "V",
    valueType: ValueType.NUMBER,
    description: "Low voltage threshold used in O2 sensor functional test.",
    formula: "A / 200",
    isMandatory: false,
  },
  {
    mode: '05',
    pidCode: '04',
    fullCode: '0504',
    key: 'o2_test_high_sensor_voltage_v',
    label: "High sensor voltage for test",
    unit: "V",
    valueType: ValueType.NUMBER,
    description: "High voltage threshold in O2 test.",
    formula: "A / 200",
    isMandatory: false,
  },
  {
    mode: '05',
    pidCode: '05',
    fullCode: '0505',
    key: 'o2_rich_to_lean_response_time_ms',
    label: "Rich-to-lean response time",
    unit: "ms",
    valueType: ValueType.NUMBER,
    description: "Milliseconds for O2 sensor to respond from rich to lean.",
    formula: "256A + B",
    isMandatory: false,
  },
  {
    mode: '05',
    pidCode: '06',
    fullCode: '0506',
    key: 'o2_lean_to_rich_response_time_ms',
    label: "Lean-to-rich response time",
    unit: "ms",
    valueType: ValueType.NUMBER,
    description: "Milliseconds for O2 sensor to respond from lean to rich.",
    formula: "256A + B",
    isMandatory: false,
  },
  {
    mode: '05',
    pidCode: '07',
    fullCode: '0507',
    key: 'o2_test_min_voltage_v',
    label: "Minimum voltage during test",
    unit: "V",
    valueType: ValueType.NUMBER,
    description: "Lowest O2 sensor voltage measured during the test cycle.",
    formula: "A / 200",
    isMandatory: false,
  },
  {
    mode: '05',
    pidCode: '08',
    fullCode: '0508',
    key: 'o2_test_max_voltage_v',
    label: "Maximum voltage during test",
    unit: "V",
    valueType: ValueType.NUMBER,
    description: "Highest O2 sensor voltage measured during test.",
    formula: "A / 200",
    isMandatory: false,
  },
  {
    mode: '05',
    pidCode: '09',
    fullCode: '0509',
    key: 'o2_time_between_transitions_ms',
    label: "Time between transitions",
    unit: "ms",
    valueType: ValueType.NUMBER,
    description: "Time between O2 sensor voltage transitions.",
    formula: "256A + B",
    isMandatory: false,
  },
  {
    mode: '06',
    pidCode: '00',
    fullCode: '0600',
    key: 'supported_test_ids',
    label: "Supported test IDs",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Bitmask of which on-board monitor test IDs are available.",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '06',
    pidCode: '01',
    fullCode: '0601',
    key: 'o2_sensor_monitor_b1s1',
    label: "O2 sensor monitor B1S1",
    unit: "Varies",
    valueType: ValueType.JSON,
    description: "On-board test result for bank 1 upstream O2 sensor.",
    formula: "See SAE J1979",
    isMandatory: false,
  },
  {
    mode: '06',
    pidCode: '02',
    fullCode: '0602',
    key: 'o2_sensor_monitor_b1s2',
    label: "O2 sensor monitor B1S2",
    unit: "Varies",
    valueType: ValueType.JSON,
    description: "On-board test result for bank 1 downstream O2 sensor.",
    formula: "See SAE J1979",
    isMandatory: false,
  },
  {
    mode: '06',
    pidCode: '21',
    fullCode: '0621',
    key: 'catalyst_monitor_b1',
    label: "Catalyst monitor B1",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Catalyst efficiency monitor test result for bank 1.",
    formula: "See SAE J1979",
    isMandatory: false,
  },
  {
    mode: '07',
    pidCode: '00',
    fullCode: '0700',
    key: 'pending_dtcs',
    label: "Request pending DTCs",
    unit: null,
    valueType: ValueType.JSON,
    description: "Returns fault codes detected during the current or last drive cycle but not yet confirmed (need 2+ cycles). Useful to catch intermittent faults before the Check Engine Light illuminates.",
    formula: "—",
    isMandatory: false,
  },
  {
    mode: '09',
    pidCode: '00',
    fullCode: '0900',
    key: 'supported_info_pids',
    label: "Supported info PIDs",
    unit: "—",
    valueType: ValueType.JSON,
    description: "Bitmask of which Mode 09 information PIDs are supported.",
    formula: "Bitmask",
    isMandatory: false,
  },
  {
    mode: '09',
    pidCode: '02',
    fullCode: '0902',
    key: 'vin',
    label: "Vehicle Identification Number (VIN)",
    unit: "17 chars",
    valueType: ValueType.STRING,
    description: "17-character VIN encoded as ASCII bytes. Essential for identifying the vehicle in fleet or logging systems.",
    formula: "ASCII bytes",
    isMandatory: true,
  },
  {
    mode: '09',
    pidCode: '04',
    fullCode: '0904',
    key: 'calibration_id',
    label: "Calibration ID",
    unit: "string",
    valueType: ValueType.STRING,
    description: "ECU software calibration identifier string.",
    formula: "ASCII",
    isMandatory: false,
  },
  {
    mode: '09',
    pidCode: '06',
    fullCode: '0906',
    key: 'calibration_verification_number',
    label: "Calibration verification number",
    unit: "—",
    valueType: ValueType.STRING,
    description: "CVN checksum to verify ECU software has not been tampered with.",
    formula: "Hex",
    isMandatory: false,
  },
  {
    mode: '09',
    pidCode: '0A',
    fullCode: '090A',
    key: 'ecu_name',
    label: "ECU name",
    unit: "string",
    valueType: ValueType.STRING,
    description: "Name of the ECU that responded — useful when multiple ECUs answer on the CAN bus.",
    formula: "ASCII",
    isMandatory: false,
  },
  {
    mode: '09',
    pidCode: '0D',
    fullCode: '090D',
    key: 'engine_serial_number',
    label: "Engine serial number",
    unit: "string",
    valueType: ValueType.STRING,
    description: "Engine serial number string (not supported on all vehicles).",
    formula: "ASCII",
    isMandatory: false,
  },
  {
    mode: '0A',
    pidCode: '00',
    fullCode: '0A00',
    key: 'permanent_dtcs',
    label: "Request permanent DTCs",
    unit: null,
    valueType: ValueType.JSON,
    description: "Returns permanent diagnostic trouble codes. These CANNOT be cleared with Mode 04. They persist until: (1) the fault is repaired, AND (2) the vehicle completes a successful emissions monitor drive cycle. Introduced to prevent inspection fraud.",
    formula: "—",
    isMandatory: false,
  },
];
