export const SUPPORTED_PID_CODES = [
  '0100',
  '0101',
  '0102',
  '0103',
  '0104',
  '0105',
  '0106',
  '0107',
  '0108',
  '0109',
  '010A',
  '010B',
  '010C',
  '010D',
  '010E',
  '010F',
  '0110',
  '0111',
  '0112',
  '0113',
  '0114',
  '0115',
  '0116',
  '0117',
  '0118',
  '0119',
  '011C',
  '011F',
  '0120',
  '0121',
  '0122',
  '0123',
  '012C',
  '012D',
  '012E',
  '012F',
  '0130',
  '0131',
  '0133',
  '013C',
  '013D',
  '013E',
  '013F',
  '0140',
  '0142',
  '0143',
  '0144',
  '0145',
  '0146',
  '0147',
  '014C',
  '014D',
  '014E',
  '0151',
  '0152',
  '015A',
  '015B',
  '015C',
  '015D',
  '015E',
  '0160',
  '0167',
  '0168',
] as const;

export const MEASUREMENT_LIBRARY: Record<
  string,
  {
    key: string;
    label: string;
    unit: string | null;
    raw: string | null;
    decoded: number | string | boolean | Record<string, unknown>;
  }
> = {
  '0100': {
    key: 'supported_pids_01_20',
    label: "Supported PIDs 01–20",
    unit: "—",
    raw: null,
    decoded: {"supported":true,"source":"Supported PIDs 01–20"},
  },
  '0101': {
    key: 'monitor_status_mil',
    label: "Monitor status (MIL)",
    unit: "—",
    raw: null,
    decoded: {"milOn":false,"storedDtcCount":0,"readiness":{"misfire":true,"fuelSystem":true,"catalyst":true}},
  },
  '0102': {
    key: 'freeze_frame_dtc',
    label: "Freeze frame DTC",
    unit: "—",
    raw: null,
    decoded: "P0172",
  },
  '0103': {
    key: 'fuel_system_status',
    label: "Fuel system status",
    unit: "—",
    raw: null,
    decoded: {"bank1":"closed_loop","bank2":"closed_loop"},
  },
  '0104': {
    key: 'engine_load',
    label: "Engine load",
    unit: "%",
    raw: null,
    decoded: 26,
  },
  '0105': {
    key: 'coolant_temp_c',
    label: "Coolant temperature",
    unit: "°C",
    raw: null,
    decoded: 93,
  },
  '0106': {
    key: 'short_term_fuel_trim_bank1',
    label: "Short-term fuel trim B1",
    unit: "%",
    raw: null,
    decoded: -3.1,
  },
  '0107': {
    key: 'long_term_fuel_trim_bank1',
    label: "Long-term fuel trim B1",
    unit: "%",
    raw: null,
    decoded: 3.1,
  },
  '0108': {
    key: 'short_term_fuel_trim_bank2',
    label: "Short-term fuel trim B2",
    unit: "%",
    raw: null,
    decoded: -2.4,
  },
  '0109': {
    key: 'long_term_fuel_trim_bank2',
    label: "Long-term fuel trim B2",
    unit: "%",
    raw: null,
    decoded: 2.7,
  },
  '010A': {
    key: 'fuel_pressure_kpa',
    label: "Fuel pressure",
    unit: "kPa",
    raw: null,
    decoded: 300,
  },
  '010B': {
    key: 'intake_manifold_pressure_kpa',
    label: "Intake manifold pressure",
    unit: "kPa",
    raw: null,
    decoded: 31,
  },
  '010C': {
    key: 'engine_rpm',
    label: "Engine RPM",
    unit: "RPM",
    raw: null,
    decoded: 860,
  },
  '010D': {
    key: 'vehicle_speed',
    label: "Vehicle speed",
    unit: "km/h",
    raw: null,
    decoded: 78,
  },
  '010E': {
    key: 'timing_advance_deg',
    label: "Timing advance",
    unit: "°",
    raw: null,
    decoded: 12,
  },
  '010F': {
    key: 'intake_air_temp_c',
    label: "Intake air temperature",
    unit: "°C",
    raw: null,
    decoded: 32,
  },
  '0110': {
    key: 'maf_g_s',
    label: "MAF air flow rate",
    unit: "g/s",
    raw: null,
    decoded: 12.4,
  },
  '0111': {
    key: 'throttle_position_pct',
    label: "Throttle position",
    unit: "%",
    raw: null,
    decoded: 18.4,
  },
  '0112': {
    key: 'secondary_air_status',
    label: "Secondary air status",
    unit: "—",
    raw: null,
    decoded: "inactive",
  },
  '0113': {
    key: 'oxygen_sensors_present',
    label: "O2 sensors present",
    unit: "—",
    raw: null,
    decoded: {"bank1":2,"bank2":2},
  },
  '0114': {
    key: 'o2_sensor_b1s1',
    label: "O2 sensor B1S1",
    unit: "V, %",
    raw: null,
    decoded: {"voltageV":0.82,"trimPct":-1.6},
  },
  '0115': {
    key: 'o2_sensor_b1s2',
    label: "O2 sensor B1S2",
    unit: "V, %",
    raw: null,
    decoded: {"voltageV":0.82,"trimPct":-1.6},
  },
  '0116': {
    key: 'o2_sensor_b1s3',
    label: "O2 sensor B1S3",
    unit: "V, %",
    raw: null,
    decoded: {"voltageV":0.82,"trimPct":-1.6},
  },
  '0117': {
    key: 'o2_sensor_b1s4',
    label: "O2 sensor B1S4",
    unit: "V, %",
    raw: null,
    decoded: {"voltageV":0.82,"trimPct":-1.6},
  },
  '0118': {
    key: 'o2_sensor_b2s1',
    label: "O2 sensor B2S1",
    unit: "V, %",
    raw: null,
    decoded: {"voltageV":0.82,"trimPct":-1.6},
  },
  '0119': {
    key: 'o2_sensor_b2s2',
    label: "O2 sensor B2S2",
    unit: "V, %",
    raw: null,
    decoded: {"voltageV":0.82,"trimPct":-1.6},
  },
  '011C': {
    key: 'obd_standard',
    label: "OBD standard",
    unit: "—",
    raw: null,
    decoded: "OBD-II / EOBD",
  },
  '011F': {
    key: 'runtime_since_engine_start_s',
    label: "Run time since engine start",
    unit: "s",
    raw: null,
    decoded: 965,
  },
  '0120': {
    key: 'supported_pids_21_40',
    label: "Supported PIDs 21–40",
    unit: "—",
    raw: null,
    decoded: {"supported":true,"source":"Supported PIDs 21–40"},
  },
  '0121': {
    key: 'distance_with_mil_on_km',
    label: "Distance with MIL on",
    unit: "km",
    raw: null,
    decoded: 24,
  },
  '0122': {
    key: 'fuel_rail_pressure_relative_kpa',
    label: "Fuel rail pressure (relative)",
    unit: "kPa",
    raw: null,
    decoded: 340,
  },
  '0123': {
    key: 'fuel_rail_pressure_direct_kpa',
    label: "Fuel rail pressure (direct)",
    unit: "kPa",
    raw: null,
    decoded: 4800,
  },
  '012C': {
    key: 'egr_commanded_pct',
    label: "EGR commanded",
    unit: "%",
    raw: null,
    decoded: 5,
  },
  '012D': {
    key: 'egr_error_pct',
    label: "EGR error",
    unit: "%",
    raw: null,
    decoded: -1.5,
  },
  '012E': {
    key: 'evap_purge_commanded_pct',
    label: "Evap purge commanded",
    unit: "%",
    raw: null,
    decoded: 17,
  },
  '012F': {
    key: 'fuel_tank_level_pct',
    label: "Fuel tank level",
    unit: "%",
    raw: null,
    decoded: 42,
  },
  '0130': {
    key: 'warmups_since_codes_cleared',
    label: "Warm-ups since codes cleared",
    unit: "count",
    raw: null,
    decoded: 14,
  },
  '0131': {
    key: 'distance_since_codes_cleared_km',
    label: "Distance since codes cleared",
    unit: "km",
    raw: null,
    decoded: 640,
  },
  '0133': {
    key: 'barometric_pressure_kpa',
    label: "Barometric pressure",
    unit: "kPa",
    raw: null,
    decoded: 99,
  },
  '013C': {
    key: 'catalyst_temp_b1s1_c',
    label: "Catalyst temp B1S1",
    unit: "°C",
    raw: null,
    decoded: 480,
  },
  '013D': {
    key: 'catalyst_temp_b2s1_c',
    label: "Catalyst temp B2S1",
    unit: "°C",
    raw: null,
    decoded: 480,
  },
  '013E': {
    key: 'catalyst_temp_b1s2_c',
    label: "Catalyst temp B1S2",
    unit: "°C",
    raw: null,
    decoded: 480,
  },
  '013F': {
    key: 'catalyst_temp_b2s2_c',
    label: "Catalyst temp B2S2",
    unit: "°C",
    raw: null,
    decoded: 480,
  },
  '0140': {
    key: 'supported_pids_41_60',
    label: "Supported PIDs 41–60",
    unit: "—",
    raw: null,
    decoded: {"supported":true,"source":"Supported PIDs 41–60"},
  },
  '0142': {
    key: 'control_module_voltage_v',
    label: "Control module voltage",
    unit: "V",
    raw: null,
    decoded: 13.8,
  },
  '0143': {
    key: 'absolute_engine_load_pct',
    label: "Absolute engine load",
    unit: "%",
    raw: null,
    decoded: 34,
  },
  '0144': {
    key: 'commanded_air_fuel_ratio_lambda',
    label: "Commanded air-fuel ratio",
    unit: "λ",
    raw: null,
    decoded: 1.01,
  },
  '0145': {
    key: 'relative_throttle_position_pct',
    label: "Relative throttle position",
    unit: "%",
    raw: null,
    decoded: 16.8,
  },
  '0146': {
    key: 'ambient_air_temp_c',
    label: "Ambient air temperature",
    unit: "°C",
    raw: null,
    decoded: 29,
  },
  '0147': {
    key: 'absolute_throttle_position_b_pct',
    label: "Absolute throttle position B",
    unit: "%",
    raw: null,
    decoded: 19.5,
  },
  '014C': {
    key: 'commanded_throttle_actuator_pct',
    label: "Commanded throttle actuator",
    unit: "%",
    raw: null,
    decoded: 21.2,
  },
  '014D': {
    key: 'time_with_mil_on_min',
    label: "Time with MIL on",
    unit: "min",
    raw: null,
    decoded: 36,
  },
  '014E': {
    key: 'time_since_codes_cleared_min',
    label: "Time since codes cleared",
    unit: "min",
    raw: null,
    decoded: 920,
  },
  '0151': {
    key: 'fuel_type',
    label: "Fuel type",
    unit: "—",
    raw: null,
    decoded: "Gasoline",
  },
  '0152': {
    key: 'ethanol_fuel_pct',
    label: "Ethanol fuel %",
    unit: "%",
    raw: null,
    decoded: 9,
  },
  '015A': {
    key: 'relative_accelerator_pedal_pct',
    label: "Relative accelerator pedal",
    unit: "%",
    raw: null,
    decoded: 22.3,
  },
  '015B': {
    key: 'hybrid_battery_pack_life_pct',
    label: "Hybrid battery pack life",
    unit: "%",
    raw: null,
    decoded: 88,
  },
  '015C': {
    key: 'engine_oil_temp_c',
    label: "Engine oil temperature",
    unit: "°C",
    raw: null,
    decoded: 101,
  },
  '015D': {
    key: 'fuel_injection_timing_deg',
    label: "Fuel injection timing",
    unit: "°",
    raw: null,
    decoded: 6.5,
  },
  '015E': {
    key: 'engine_fuel_rate_lph',
    label: "Engine fuel rate",
    unit: "L/h",
    raw: null,
    decoded: 2.7,
  },
  '0160': {
    key: 'supported_pids_61_80',
    label: "Supported PIDs 61–80",
    unit: "—",
    raw: null,
    decoded: {"supported":true,"source":"Supported PIDs 61–80"},
  },
  '0167': {
    key: 'coolant_temp_sensor_2_c',
    label: "Engine coolant temp (sensor 2)",
    unit: "°C",
    raw: null,
    decoded: 89,
  },
  '0168': {
    key: 'fuel_rail_absolute_pressure_kpa',
    label: "Fuel rail absolute pressure",
    unit: "kPa",
    raw: null,
    decoded: 5100,
  },
};
